// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanad.Modules.CareHomes.Infrastructure.Persistence;

#nullable disable

namespace Sanad.Modules.CareHomes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CareHomesDbContext))]
    [Migration("20261002150725_AddCareHomeInventory")]
    partial class AddCareHomeInventory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("care_homes")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeBed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("RoomId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ux_care_homes_beds_room_label");

                    b.ToTable("beds", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.Property<string>("PrivateStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("private_storage_key");

                    b.Property<Guid>("ProfileRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_revision_id");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.Property<bool>("VerifiedNonExpiring")
                        .HasColumnType("boolean")
                        .HasColumnName("verified_non_expiring");

                    b.Property<DateTime?>("VerifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_on_utc");

                    b.Property<Guid>("care_home_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("care_home_id", "ProfileRevisionId", "Type");

                    b.ToTable("documents", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_revision_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmittedRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_revision_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("facilities", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeMaintenanceBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId", "Target", "TargetId");

                    b.ToTable("maintenance_blocks", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeProfileRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("address");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("amenities_json");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_on_utc");

                    b.Property<string>("ArabicAdmissionConditions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("arabic_admission_conditions");

                    b.Property<string>("ArabicDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("arabic_description");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arabic_name");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("area");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_phone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishAdmissionConditions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("english_admission_conditions");

                    b.Property<string>("EnglishDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("english_description");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("governorate");

                    b.Property<string>("MedicalServices")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medical_services_json");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<DateTime?>("SubmittedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_on_utc");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<Guid>("care_home_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("care_home_id", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("profile_revisions", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer")
                        .HasColumnName("new_status");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("integer")
                        .HasColumnName("previous_status");

                    b.Property<Guid?>("ProfileRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_revision_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("care_home_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("care_home_id");

                    b.ToTable("review_history", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("FacilityId", "RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_care_homes_rooms_facility_room_number");

                    b.ToTable("rooms", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocationMode")
                        .HasColumnType("integer");

                    b.Property<string>("ArabicDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnglishDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyPriceEgp")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId", "EnglishName");

                    b.ToTable("room_types", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeBed", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoom", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeDocument", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany("Documents")
                        .HasForeignKey("care_home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeMaintenanceBlock", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeProfileRevision", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany("Revisions")
                        .HasForeignKey("care_home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeReviewHistory", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany("ReviewHistory")
                        .HasForeignKey("care_home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoom", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoomType", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ReviewHistory");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
