// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanad.Modules.CareHomes.Infrastructure.Persistence;

#nullable disable

namespace Sanad.Modules.CareHomes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CareHomesDbContext))]
    [Migration("20261008141359_AddCareHomeFinanceReporting")]
    partial class AddCareHomeFinanceReporting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("care_homes")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBooking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ActualCheckInOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_check_in_on_utc");

                    b.Property<Guid?>("ActualCheckInRecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("actual_check_in_recorded_by");

                    b.Property<DateTime?>("ActualCheckOutOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_check_out_on_utc");

                    b.Property<Guid?>("ActualCheckOutRecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("actual_check_out_recorded_by");

                    b.Property<Guid?>("AssignedBedId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_bed_id");

                    b.Property<Guid?>("AssignedRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_room_id");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CareNeedsNotes")
                        .HasColumnType("text");

                    b.Property<int>("ChargeRuleVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CheckoutHoldUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DecisionHoldUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("text");

                    b.Property<DateTime>("EarliestArrivalUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("earliest_arrival_utc");

                    b.Property<int>("ElderlyAge")
                        .HasColumnType("integer");

                    b.Property<string>("ElderlyArabicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ElderlyEnglishName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ElderlyId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("ExtensionOfBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("extension_of_booking_id");

                    b.Property<Guid?>("ExtensionRootBookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("extension_root_booking_id");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FamilyCheckInConfirmedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("family_check_in_confirmed_by");

                    b.Property<DateTime?>("FamilyCheckInConfirmedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("family_check_in_confirmed_on_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("IntentionOrderId")
                        .HasColumnType("text")
                        .HasColumnName("intention_order_id");

                    b.Property<string>("MedicalSnapshotJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("MerchantReference")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("PaymentClientSecret")
                        .HasColumnType("text")
                        .HasColumnName("payment_client_secret");

                    b.Property<DateTime?>("PaymentCompletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_completed_on_utc");

                    b.Property<DateTime?>("PaymentIntentClaimedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_intent_claimed_on_utc");

                    b.Property<int?>("PaymentIntentMethod")
                        .HasColumnType("integer")
                        .HasColumnName("payment_intent_method");

                    b.Property<string>("PaymentPublicKey")
                        .HasColumnType("text")
                        .HasColumnName("payment_public_key");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PaymobOrderId")
                        .HasColumnType("text")
                        .HasColumnName("paymob_order_id");

                    b.Property<long?>("PaymobTransactionId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PlatformFeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("RefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("refund_amount");

                    b.Property<DateTime?>("RefundClaimedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refund_claimed_on_utc");

                    b.Property<Guid?>("RefundCompletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("refund_completed_by");

                    b.Property<DateTime?>("RefundCompletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refund_completed_on_utc");

                    b.Property<string>("RefundFailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("refund_failure_reason");

                    b.Property<string>("RefundReference")
                        .HasColumnType("text");

                    b.Property<int>("RefundStatus")
                        .HasColumnType("integer")
                        .HasColumnName("refund_status");

                    b.Property<string>("ResponsibleContactName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("ResponsibleContactRelationship")
                        .HasColumnType("text");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExtensionOfBookingId");

                    b.HasIndex("MerchantReference")
                        .IsUnique();

                    b.HasIndex("ExtensionRootBookingId", "StartDate");

                    b.HasIndex("FacilityId", "Status", "StartDate", "EndDate");

                    b.ToTable("bookings", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBookingAssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Actor")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<Guid?>("FromBedId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_bed_id");

                    b.Property<Guid?>("FromRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_room_id");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<Guid?>("ToBedId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_bed_id");

                    b.Property<Guid>("ToRoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_room_id");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "EffectiveDate")
                        .IsUnique()
                        .HasFilter("\"from_room_id\" IS NOT NULL");

                    b.ToTable("booking_assignment_history", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeCheckInDispute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CheckoutOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveCheckInOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidence")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("FamilyReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("OpenedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OpenedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "Status")
                        .IsUnique()
                        .HasFilter("\"Status\" = 1");

                    b.ToTable("check_in_disputes", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeInternalBookingNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("Author")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("BookingId", "CreatedOnUtc");

                    b.ToTable("internal_booking_notes", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomePayout", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<int>("ChargeRuleVersion")
                        .HasColumnType("integer")
                        .HasColumnName("charge_rule_version");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("evidence");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<decimal>("FeeAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("fee_amount");

                    b.Property<decimal>("FeeRatePercentage")
                        .HasPrecision(9, 4)
                        .HasColumnType("numeric(9,4)")
                        .HasColumnName("fee_rate_percentage");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<decimal>("NetAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("net_amount");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<DateTime>("RecordedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_on_utc");

                    b.Property<decimal>("RemainingCustomerAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("remaining_customer_amount");

                    b.Property<string>("TransferReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transfer_reference");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("FacilityId", "RecordedOnUtc");

                    b.ToTable("payouts", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomePayoutDebt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<decimal>("CustomerRefundAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("customer_refund_amount");

                    b.Property<Guid>("PayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("RecordedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("recorded_by");

                    b.Property<DateTime>("RecordedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_on_utc");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reference");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("PayoutId", "Reference")
                        .IsUnique();

                    b.ToTable("payout_debts", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeRating", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CareHomeId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("ReviewText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_text");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.HasIndex("CareHomeId", "Stars");

                    b.ToTable("ratings", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeTransferNotificationOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid?>("ClaimToken")
                        .HasColumnType("uuid")
                        .HasColumnName("claim_token");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("LastAttemptOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempt_on_utc");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("NextAttemptOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_on_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TransferId")
                        .HasColumnType("uuid")
                        .HasColumnName("transfer_id");

                    b.HasKey("Id");

                    b.HasIndex("TransferId")
                        .IsUnique();

                    b.HasIndex("Status", "NextAttemptOnUtc");

                    b.ToTable("transfer_notification_outbox", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeBed", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("RoomId", "Label")
                        .IsUnique()
                        .HasDatabaseName("ux_care_homes_beds_room_label");

                    b.ToTable("beds", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.Property<string>("PrivateStorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("private_storage_key");

                    b.Property<Guid>("ProfileRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_revision_id");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<Guid?>("VerifiedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_user_id");

                    b.Property<bool>("VerifiedNonExpiring")
                        .HasColumnType("boolean")
                        .HasColumnName("verified_non_expiring");

                    b.Property<DateTime?>("VerifiedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_on_utc");

                    b.Property<Guid>("care_home_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("care_home_id", "ProfileRevisionId", "Type");

                    b.ToTable("documents", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ApprovedRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_revision_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmittedRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submitted_revision_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("facilities", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeMaintenanceBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<DateTime?>("CancelledOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_on_utc");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Target")
                        .HasColumnType("integer");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId", "Target", "TargetId");

                    b.ToTable("maintenance_blocks", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeProfileMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content_type");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<long>("Length")
                        .HasColumnType("bigint")
                        .HasColumnName("length");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProfileRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_revision_id");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.HasKey("Id");

                    b.HasIndex("ProfileRevisionId", "Kind", "Position")
                        .IsUnique();

                    b.ToTable("profile_media", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeProfileRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("address");

                    b.Property<string>("Amenities")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("amenities_json");

                    b.Property<DateTime?>("ApprovedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_on_utc");

                    b.Property<string>("ArabicAdmissionConditions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("arabic_admission_conditions");

                    b.Property<string>("ArabicDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("arabic_description");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arabic_name");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("area");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("contact_phone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishAdmissionConditions")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("english_admission_conditions");

                    b.Property<string>("EnglishDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("english_description");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_name");

                    b.Property<string>("Governorate")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("governorate");

                    b.Property<string>("MedicalServices")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("medical_services_json");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revision_number");

                    b.Property<DateTime?>("SubmittedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_on_utc");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<Guid>("care_home_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("care_home_id", "RevisionNumber")
                        .IsUnique();

                    b.ToTable("profile_revisions", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeReviewHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<int>("NewStatus")
                        .HasColumnType("integer")
                        .HasColumnName("new_status");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_on_utc");

                    b.Property<int>("PreviousStatus")
                        .HasColumnType("integer")
                        .HasColumnName("previous_status");

                    b.Property<Guid?>("ProfileRevisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_revision_id");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("care_home_id")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("care_home_id");

                    b.ToTable("review_history", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("RoomTypeId")
                        .HasColumnType("uuid")
                        .HasColumnName("room_type_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.HasIndex("FacilityId", "RoomNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_care_homes_rooms_facility_room_number");

                    b.ToTable("rooms", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoomType", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AllocationMode")
                        .HasColumnType("integer");

                    b.Property<string>("ArabicDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnglishDescription")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("care_home_id");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MonthlyPriceEgp")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId", "EnglishName");

                    b.ToTable("room_types", "care_homes");
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBooking", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBooking", null)
                        .WithMany()
                        .HasForeignKey("ExtensionOfBookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBooking", null)
                        .WithMany()
                        .HasForeignKey("ExtensionRootBookingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeInternalBookingNote", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBooking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomePayout", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBooking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomePayoutDebt", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBooking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Bookings.CareHomePayout", null)
                        .WithMany()
                        .HasForeignKey("PayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeRating", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Bookings.CareHomeBooking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("CareHomeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeBed", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoom", null)
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeDocument", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany("Documents")
                        .HasForeignKey("care_home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeMaintenanceBlock", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeProfileMedia", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeProfileRevision", null)
                        .WithMany()
                        .HasForeignKey("ProfileRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeProfileRevision", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany("Revisions")
                        .HasForeignKey("care_home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeReviewHistory", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany("ReviewHistory")
                        .HasForeignKey("care_home_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoom", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoomType", null)
                        .WithMany()
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeRoomType", b =>
                {
                    b.HasOne("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.CareHomes.Domain.Facilities.CareHomeFacility", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("ReviewHistory");

                    b.Navigation("Revisions");
                });
#pragma warning restore 612, 618
        }
    }
}
