using Microsoft.EntityFrameworkCore;
using Sanad.BuildingBlocks.Application.CQRS;
using Sanad.BuildingBlocks.Application.Results;
using Sanad.BuildingBlocks.Domain.Exceptions;
using Sanad.BuildingBlocks.Domain.Primitives.Ids;
using Sanad.Modules.CareHomes.Application.Abstractions.Data;
using Sanad.Modules.CareHomes.Domain.Facilities;

namespace Sanad.Modules.CareHomes.Application.Inventory;

internal static class InventoryMutation
{
    internal static async Task<(CareHomeFacility? Facility, Result<CareHomeInventoryDto>? Failure)> Load(ICareHomesDbContext db, UserId actor, int version, CancellationToken ct)
    {
        var f = await db.Facilities.SingleOrDefaultAsync(x => x.OwnerUserId == actor, ct);
        if (f is null) return (null, Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.NotFound", "Facility was not found.")));
        try { f.EnsureInventoryAccess(actor, version); return (f, null); }
        catch (DomainException ex) { return (f, Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Conflict", ex.Message))); }
    }
    internal static async Task<Result<CareHomeInventoryDto>> Save(ICareHomesDbContext db, CareHomeFacility f, CancellationToken ct)
    {
        f.RecordInventoryChange(DateTime.UtcNow);
        try { await db.SaveChangesAsync(ct); }
        catch (DbUpdateConcurrencyException) { return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Conflict", "Inventory changed; reload before editing.")); }
        catch (DbUpdateException ex) when (IsInventoryUniqueRace(ex)) { return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Conflict", "The room number or bed label is already used.")); }
        return await InventoryHandlerSupport.Map(db, f.Id, ct);
    }

    private static bool IsInventoryUniqueRace(Exception exception)
    {
        for (Exception? current = exception; current is not null; current = current.InnerException)
        {
            if (!string.Equals(current.GetType().Name, "PostgresException", StringComparison.Ordinal)) continue;
            string? constraint = current.GetType().GetProperty("ConstraintName")?.GetValue(current)?.ToString();
            if (constraint is "ux_care_homes_rooms_facility_room_number" or "ux_care_homes_beds_room_label") return true;
        }
        return false;
    }
}

public sealed class UpdateRoomTypeCommandHandler(ICareHomesDbContext db) : ICommandHandler<UpdateRoomTypeCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(UpdateRoomTypeCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; var x = await db.RoomTypes.SingleOrDefaultAsync(x => x.Id == r.RoomTypeId && x.FacilityId == f!.Id, ct); if (x is null) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.NotFound", "Room type was not found.")); try { x.Update(r.ArabicName, r.EnglishName, r.MonthlyPriceEgp, r.AllocationMode, r.ArabicDescription, r.EnglishDescription, DateTime.UtcNow); return await InventoryMutation.Save(db, f!, ct); } catch (ArgumentException ex) { return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Invalid", ex.Message)); } } }
public sealed class ArchiveRoomTypeCommandHandler(ICareHomesDbContext db) : ICommandHandler<ArchiveRoomTypeCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(ArchiveRoomTypeCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; var x = await db.RoomTypes.SingleOrDefaultAsync(x => x.Id == r.RoomTypeId && x.FacilityId == f!.Id, ct); if (x is null) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.NotFound", "Room type was not found.")); if (r.Restore) x.Restore(DateTime.UtcNow); else x.Archive(DateTime.UtcNow); return await InventoryMutation.Save(db, f!, ct); } }
public sealed class CreateRoomCommandHandler(ICareHomesDbContext db) : ICommandHandler<CreateRoomCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(CreateRoomCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; if (!await db.RoomTypes.AnyAsync(x => x.Id == r.RoomTypeId && x.FacilityId == f!.Id && !x.IsArchived, ct)) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.InvalidTarget", "Room type was not found or is archived.")); if (await db.Rooms.AnyAsync(x => x.FacilityId == f!.Id && x.RoomNumber == r.RoomNumber.Trim(), ct)) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.RoomNumberTaken", "Room number is already used by this facility.")); try { db.Rooms.Add(CareHomeRoom.Create(f!.Id, r.RoomTypeId, r.RoomNumber, DateTime.UtcNow)); return await InventoryMutation.Save(db, f, ct); } catch (ArgumentException ex) { return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Invalid", ex.Message)); } } }
public sealed class RenameRoomCommandHandler(ICareHomesDbContext db, ICareHomeOccupancyProvider occupancy) : ICommandHandler<RenameRoomCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(RenameRoomCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; var x = await db.Rooms.SingleOrDefaultAsync(x => x.Id == r.RoomId && x.FacilityId == f!.Id, ct); if (x is null) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.NotFound", "Room was not found.")); if (await db.Rooms.AnyAsync(y => y.FacilityId == f!.Id && y.Id != x.Id && y.RoomNumber == r.RoomNumber.Trim(), ct)) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.RoomNumberTaken", "Room number is already used by this facility.")); var active = await occupancy.GetActiveAsync(f!.Id, ct); var bedIds = await db.Beds.Where(b => b.RoomId == x.Id).Select(b => b.Id).ToListAsync(ct); if (active.Any(o => (o.ResourceKind == CareHomeResourceKind.Room && o.ResourceId == x.Id) || (o.ResourceKind == CareHomeResourceKind.Bed && bedIds.Contains(o.ResourceId)))) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.ActiveOccupancy", "Room number cannot change while an active hold or stay exists.")); try { x.Rename(r.RoomNumber, false, DateTime.UtcNow); return await InventoryMutation.Save(db, f, ct); } catch (Exception ex) when (ex is ArgumentException or InvalidOperationException) { return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Invalid", ex.Message)); } } }
public sealed class ArchiveRoomCommandHandler(ICareHomesDbContext db) : ICommandHandler<ArchiveRoomCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(ArchiveRoomCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; var x = await db.Rooms.SingleOrDefaultAsync(x => x.Id == r.RoomId && x.FacilityId == f!.Id, ct); if (x is null) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.NotFound", "Room was not found.")); if (r.Restore) x.Restore(DateTime.UtcNow); else x.Archive(DateTime.UtcNow); return await InventoryMutation.Save(db, f!, ct); } }
public sealed class CreateBedCommandHandler(ICareHomesDbContext db) : ICommandHandler<CreateBedCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(CreateBedCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; if (!await db.Rooms.AnyAsync(x => x.Id == r.RoomId && x.FacilityId == f!.Id && !x.IsArchived, ct)) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.InvalidTarget", "Room was not found or is archived.")); if (await db.Beds.AnyAsync(x => x.RoomId == r.RoomId && x.Label == r.Label.Trim(), ct)) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.LabelTaken", "Bed label is already used in this room.")); try { db.Beds.Add(CareHomeBed.Create(f!.Id, r.RoomId, r.Label, DateTime.UtcNow)); return await InventoryMutation.Save(db, f, ct); } catch (ArgumentException ex) { return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Invalid", ex.Message)); } } }
public sealed class RenameBedCommandHandler(ICareHomesDbContext db) : ICommandHandler<RenameBedCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(RenameBedCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; var x = await db.Beds.SingleOrDefaultAsync(x => x.Id == r.BedId && x.FacilityId == f!.Id, ct); if (x is null) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.NotFound", "Bed was not found.")); if (await db.Beds.AnyAsync(y => y.RoomId == x.RoomId && y.Id != x.Id && y.Label == r.Label.Trim(), ct)) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.LabelTaken", "Bed label is already used in this room.")); try { x.Rename(r.Label, DateTime.UtcNow); return await InventoryMutation.Save(db, f!, ct); } catch (ArgumentException ex) { return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Invalid", ex.Message)); } } }
public sealed class ArchiveBedCommandHandler(ICareHomesDbContext db) : ICommandHandler<ArchiveBedCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(ArchiveBedCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; var x = await db.Beds.SingleOrDefaultAsync(x => x.Id == r.BedId && x.FacilityId == f!.Id, ct); if (x is null) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.NotFound", "Bed was not found.")); if (r.Restore) x.Restore(DateTime.UtcNow); else x.Archive(DateTime.UtcNow); return await InventoryMutation.Save(db, f!, ct); } }
public sealed class CreateMaintenanceBlockCommandHandler(ICareHomesDbContext db, ICareHomeOccupancyProvider occupancy) : ICommandHandler<CreateMaintenanceBlockCommand, CareHomeInventoryDto>
{ public async Task<Result<CareHomeInventoryDto>> Handle(CreateMaintenanceBlockCommand r, CancellationToken ct) { var (f, fail) = await InventoryMutation.Load(db, r.Actor, r.ExpectedVersion, ct); if (fail is not null) return fail; var roomId = r.Target == CareHomeMaintenanceTarget.Room ? r.TargetId : await db.Beds.Where(x => x.Id == r.TargetId && x.FacilityId == f!.Id).Select(x => (Guid?)x.RoomId).SingleOrDefaultAsync(ct); bool targetExists = roomId is not null && (r.Target == CareHomeMaintenanceTarget.Room ? await db.Rooms.AnyAsync(x => x.Id == r.TargetId && x.FacilityId == f!.Id && !x.IsArchived, ct) : await db.Beds.AnyAsync(x => x.Id == r.TargetId && x.FacilityId == f!.Id && !x.IsArchived, ct)); if (!targetExists) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.InvalidTarget", "Maintenance target was not found, or is archived, in this facility.")); var active = await occupancy.GetActiveAsync(f!.Id, ct); var bedIds = await db.Beds.Where(x => x.RoomId == roomId.GetValueOrDefault() && !x.IsArchived).Select(x => x.Id).ToListAsync(ct); bool activeConflict = active.Any(o => o.Overlaps(r.StartDate, r.EndDate) && ((r.Target == CareHomeMaintenanceTarget.Room && ((o.ResourceKind == CareHomeResourceKind.Room && o.ResourceId == r.TargetId) || (o.ResourceKind == CareHomeResourceKind.Bed && bedIds.Contains(o.ResourceId)))) || (r.Target == CareHomeMaintenanceTarget.Bed && o.ResourceKind == CareHomeResourceKind.Bed && o.ResourceId == r.TargetId))); if (activeConflict) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.ActiveOccupancy", "Maintenance cannot overlap an active hold or stay.")); var blocks = await db.MaintenanceBlocks.Where(x => x.FacilityId == f.Id && x.StartDate < r.EndDate && x.EndDate > r.StartDate).ToListAsync(ct); if (blocks.Any(x => (x.Target == r.Target && x.TargetId == r.TargetId) || (r.Target == CareHomeMaintenanceTarget.Room && x.Target == CareHomeMaintenanceTarget.Bed && bedIds.Contains(x.TargetId)) || (r.Target == CareHomeMaintenanceTarget.Bed && x.Target == CareHomeMaintenanceTarget.Room && x.TargetId == roomId.GetValueOrDefault()))) return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Overlap", "Maintenance blocks cannot overlap on a room or its beds.")); try { db.MaintenanceBlocks.Add(CareHomeMaintenanceBlock.Create(f.Id, r.Target, r.TargetId, r.StartDate, r.EndDate, r.Reason, DateTime.UtcNow)); return await InventoryMutation.Save(db, f, ct); } catch (ArgumentException ex) { return Result<CareHomeInventoryDto>.Failure(new Error("CareHomes.Inventory.Invalid", ex.Message)); } } }
