// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanad.Modules.Families.Infrastructure.Persistence;

#nullable disable

namespace Sanad.Modules.Families.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FamiliesDbContext))]
    [Migration("20260902022127_AddElderlyRelationshipType")]
    partial class AddElderlyRelationshipType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("families")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Elderlies.Elderly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arabic_full_name");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DetailedAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detailed_address");

                    b.Property<string>("EnglishFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_full_name");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("HealthNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("health_notes");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ProfileImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_key");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("elderlies", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("families", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Invitations.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_on_utc");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("invited_email");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("family_invitations", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Families.Family", b =>
                {
                    b.OwnsMany("Sanad.Modules.Families.Domain.Families.FamilyMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("FamilyId")
                                .HasColumnType("uuid")
                                .HasColumnName("family_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("AddedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("added_by_user_id");

                            b1.Property<DateTime>("JoinedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_on_utc");

                            b1.Property<int>("RelationshipType")
                                .HasColumnType("integer")
                                .HasColumnName("relationship_type");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.HasKey("FamilyId", "Id");

                            b1.ToTable("family_members", "families");

                            b1.WithOwner()
                                .HasForeignKey("FamilyId");
                        });

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
