// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanad.Modules.Families.Infrastructure.Persistence;

#nullable disable

namespace Sanad.Modules.Families.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FamiliesDbContext))]
    [Migration("20260902083751_AddElderlyMedifcalProfile")]
    partial class AddElderlyMedifcalProfile
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("families")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arabic_text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("english_text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Order");

                    b.ToTable("assessment_questions", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.AssessmentTier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicButtonText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("arabic_button_text");

                    b.Property<string>("ArabicRecommendations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_recommendations");

                    b.Property<string>("ArabicSubtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arabic_subtitle");

                    b.Property<string>("ArabicTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arabic_title");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("background_color");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishButtonText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("english_button_text");

                    b.Property<string>("EnglishRecommendations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_recommendations");

                    b.Property<string>("EnglishSubtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("english_subtitle");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_title");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<int>("MinScore")
                        .HasColumnType("integer")
                        .HasColumnName("min_score");

                    b.Property<int>("ScreenOrder")
                        .HasColumnType("integer")
                        .HasColumnName("screen_order");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "ScreenOrder");

                    b.ToTable("assessment_tiers", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.CareAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_tier_id");

                    b.Property<DateTime>("CompletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on_utc");

                    b.Property<Guid?>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.HasIndex("ElderlyId");

                    b.HasIndex("FamilyId");

                    b.ToTable("care_assessments", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Elderlies.Elderly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arabic_full_name");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DetailedAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detailed_address");

                    b.Property<string>("EnglishFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_full_name");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("HealthNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("health_notes");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ProfileImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_key");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("elderlies", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("families", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Invitations.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_on_utc");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("invited_email");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("family_invitations", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.AssessmentQuestion", b =>
                {
                    b.OwnsMany("Sanad.Modules.Families.Domain.Assessments.AssessmentOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ArabicText")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("arabic_text");

                            b1.Property<string>("EnglishText")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("english_text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid")
                                .HasColumnName("question_id");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer")
                                .HasColumnName("weight");

                            b1.HasKey("Id");

                            b1.HasIndex("QuestionId", "Order");

                            b1.ToTable("assessment_options", "families");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.CareAssessment", b =>
                {
                    b.OwnsMany("Sanad.Modules.Families.Domain.Assessments.CareAssessmentAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assessment_id");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid")
                                .HasColumnName("question_id");

                            b1.Property<int>("ScoreSnapshot")
                                .HasColumnType("integer")
                                .HasColumnName("score_snapshot");

                            b1.Property<Guid>("SelectedOptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("selected_option_id");

                            b1.HasKey("Id");

                            b1.HasIndex("AssessmentId");

                            b1.ToTable("care_assessment_answers", "families");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");
                        });

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Elderlies.Elderly", b =>
                {
                    b.OwnsOne("Sanad.Modules.Families.Domain.Elderlies.Medical.ElderlyMedicalProfile", "MedicalProfile", b1 =>
                        {
                            b1.Property<Guid>("ElderlyId")
                                .HasColumnType("uuid")
                                .HasColumnName("elderly_id");

                            b1.Property<string>("Allergies")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("allergies");

                            b1.Property<int>("BloodType")
                                .HasColumnType("integer")
                                .HasColumnName("blood_type");

                            b1.Property<string>("ChronicConditions")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("chronic_conditions");

                            b1.Property<int?>("HeightCm")
                                .HasColumnType("integer")
                                .HasColumnName("height_cm");

                            b1.Property<string>("MedicalHistory")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("medical_history");

                            b1.Property<DateTime>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on_utc");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)")
                                .HasColumnName("weight_kg");

                            b1.HasKey("ElderlyId");

                            b1.ToTable("elderly_medical_profiles", "families");

                            b1.WithOwner()
                                .HasForeignKey("ElderlyId");
                        });

                    b.Navigation("MedicalProfile");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Families.Family", b =>
                {
                    b.OwnsMany("Sanad.Modules.Families.Domain.Families.FamilyMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("FamilyId")
                                .HasColumnType("uuid")
                                .HasColumnName("family_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("AddedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("added_by_user_id");

                            b1.Property<DateTime>("JoinedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_on_utc");

                            b1.Property<int>("RelationshipType")
                                .HasColumnType("integer")
                                .HasColumnName("relationship_type");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.HasKey("FamilyId", "Id");

                            b1.ToTable("family_members", "families");

                            b1.WithOwner()
                                .HasForeignKey("FamilyId");
                        });

                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
