// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanad.Modules.Families.Infrastructure.Persistence;

#nullable disable

namespace Sanad.Modules.Families.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FamiliesDbContext))]
    [Migration("20260924134529_AddSubscriptionInvoices")]
    partial class AddSubscriptionInvoices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("families")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Activities.ElderlyActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer")
                        .HasColumnName("activity_type");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("ElderlyId", "CreatedOnUtc");

                    b.ToTable("elderly_activity_logs", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.AssessmentQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arabic_text");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("english_text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "Order");

                    b.ToTable("assessment_questions", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.AssessmentTier", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicButtonText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("arabic_button_text");

                    b.Property<string>("ArabicRecommendations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("arabic_recommendations");

                    b.Property<string>("ArabicSubtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("arabic_subtitle");

                    b.Property<string>("ArabicTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arabic_title");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("background_color");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishButtonText")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("english_button_text");

                    b.Property<string>("EnglishRecommendations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("english_recommendations");

                    b.Property<string>("EnglishSubtitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("english_subtitle");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_title");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer")
                        .HasColumnName("max_score");

                    b.Property<int>("MinScore")
                        .HasColumnType("integer")
                        .HasColumnName("min_score");

                    b.Property<int>("ScreenOrder")
                        .HasColumnType("integer")
                        .HasColumnName("screen_order");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("IsActive", "ScreenOrder");

                    b.ToTable("assessment_tiers", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.CareAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessmentTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_tier_id");

                    b.Property<DateTime>("CompletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on_utc");

                    b.Property<Guid?>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("TotalScore")
                        .HasColumnType("integer")
                        .HasColumnName("total_score");

                    b.HasKey("Id");

                    b.HasIndex("ElderlyId");

                    b.HasIndex("FamilyId");

                    b.ToTable("care_assessments", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Bookings.Booking", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AcceptanceDeadlineUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acceptance_deadline_utc");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date")
                        .HasColumnName("booking_date");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_on_utc");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("caregiver_id");

                    b.Property<string>("CaregiverNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("caregiver_notes");

                    b.Property<int>("CaregiverType")
                        .HasColumnType("integer")
                        .HasColumnName("caregiver_type");

                    b.Property<DateTime?>("CompletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on_utc");

                    b.Property<DateTime?>("ConfirmedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_on_utc");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTime?>("ExpiredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expired_on_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime?>("PaidOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_on_utc");

                    b.Property<string>("PaymobOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_order_id");

                    b.Property<string>("PaymobRefundTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_refund_transaction_id");

                    b.Property<string>("PaymobTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_transaction_id");

                    b.Property<DateTime?>("RefundedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refunded_on_utc");

                    b.Property<string>("ServiceAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("service_address");

                    b.Property<int>("ShiftType")
                        .HasColumnType("integer")
                        .HasColumnName("shift_type");

                    b.Property<string>("SpecialInstructions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("special_instructions");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime?>("StartedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverId");

                    b.HasIndex("ElderlyId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("Status");

                    b.ToTable("bookings", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Bookings.BookingCancellationFact", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Action")
                        .HasColumnType("integer")
                        .HasColumnName("action");

                    b.Property<int>("ActorSide")
                        .HasColumnType("integer")
                        .HasColumnName("actor_side");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CancelledOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_on_utc");

                    b.Property<DateTime?>("ConfirmedOnUtcUsed")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmed_on_utc_used");

                    b.Property<bool>("IsCaregiverIncident")
                        .HasColumnType("boolean")
                        .HasColumnName("is_caregiver_incident");

                    b.Property<int>("PolicyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("policy_version");

                    b.Property<int?>("ReasonCategory")
                        .HasColumnType("integer")
                        .HasColumnName("reason_category");

                    b.Property<string>("ReasonNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason_note");

                    b.Property<int>("RefundDecisionReason")
                        .HasColumnType("integer")
                        .HasColumnName("refund_decision_reason");

                    b.Property<int>("RefundEntitlement")
                        .HasColumnType("integer")
                        .HasColumnName("refund_entitlement");

                    b.Property<int>("StatusAtCancellation")
                        .HasColumnType("integer")
                        .HasColumnName("status_at_cancellation");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_booking_cancellation_facts_booking");

                    b.ToTable("booking_cancellation_facts", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Elderlies.Elderly", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("arabic_full_name");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DetailedAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detailed_address");

                    b.Property<string>("EnglishFullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("english_full_name");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<int>("Gender")
                        .HasColumnType("integer")
                        .HasColumnName("gender");

                    b.Property<string>("HealthNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("health_notes");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("ProfileImageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_key");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("elderlies", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Families.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_on_utc");

                    b.Property<string>("DeletionMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("deletion_message");

                    b.Property<string>("DeletionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("deletion_reason");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId")
                        .IsUnique();

                    b.ToTable("families", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Invitations.FamilyInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime?>("DecidedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_on_utc");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("InvitedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("invited_email");

                    b.Property<Guid>("InvitedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_user_id");

                    b.Property<int>("RelationshipType")
                        .HasColumnType("integer")
                        .HasColumnName("relationship_type");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("InvitedUserId");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("family_invitations", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Medications.Medication", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("dosage");

                    b.Property<int>("DoseQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("dose_quantity");

                    b.PrimitiveCollection<TimeOnly[]>("DoseTimes")
                        .IsRequired()
                        .HasColumnType("time without time zone[]")
                        .HasColumnName("dose_times");

                    b.Property<string>("DoseUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("dose_unit");

                    b.Property<Guid>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("instructions");

                    b.Property<int?>("LowStockThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("low_stock_threshold");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<int?>("StockQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("stock_quantity");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("ElderlyId");

                    b.HasIndex("Status");

                    b.ToTable("medications", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Medications.MedicationDoseLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<Guid>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<Guid?>("LoggedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("logged_by_user_id");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("medication_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date")
                        .HasColumnName("scheduled_date");

                    b.Property<TimeOnly>("ScheduledTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("scheduled_time");

                    b.Property<DateTime?>("SkippedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("skipped_at_utc");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TakenAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("taken_at_utc");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("MedicationId");

                    b.HasIndex("Status");

                    b.HasIndex("ElderlyId", "ScheduledDate");

                    b.ToTable("medication_dose_logs", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Notes.ElderlyNote", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedOnUtc");

                    b.HasIndex("ElderlyId");

                    b.ToTable("elderly_notes", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Reports.MedicalReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Assessment")
                        .HasColumnType("integer")
                        .HasColumnName("assessment");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("caregiver_id");

                    b.Property<int>("CaregiverType")
                        .HasColumnType("integer")
                        .HasColumnName("caregiver_type");

                    b.Property<Guid>("CaregiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("caregiver_user_id");

                    b.Property<int?>("Diastolic")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic");

                    b.Property<Guid>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<DateTime?>("MeasurementTakenOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("measurement_taken_on_utc");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PhotoConsentAttestedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("photo_consent_attested_on_utc");

                    b.Property<Guid>("PhotoConsentCaregiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("photo_consent_caregiver_user_id");

                    b.Property<bool>("PhotoConsentConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("photo_consent_confirmed");

                    b.Property<string>("PhotoKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("photo_key");

                    b.Property<int?>("Pulse")
                        .HasColumnType("integer")
                        .HasColumnName("pulse");

                    b.Property<DateTime>("SubmittedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_on_utc");

                    b.Property<int?>("Systolic")
                        .HasColumnType("integer")
                        .HasColumnName("systolic");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_medical_reports_booking");

                    b.HasIndex("ElderlyId");

                    b.HasIndex("FamilyId", "SubmittedOnUtc");

                    b.ToTable("medical_reports", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Reports.VisitReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Activities")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("activities");

                    b.Property<int>("Assessment")
                        .HasColumnType("integer")
                        .HasColumnName("assessment");

                    b.Property<Guid>("BookingId")
                        .HasColumnType("uuid")
                        .HasColumnName("booking_id");

                    b.Property<Guid>("CaregiverId")
                        .HasColumnType("uuid")
                        .HasColumnName("caregiver_id");

                    b.Property<int>("CaregiverType")
                        .HasColumnType("integer")
                        .HasColumnName("caregiver_type");

                    b.Property<Guid>("CaregiverUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("caregiver_user_id");

                    b.Property<DateTime>("CompletedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_on_utc");

                    b.Property<Guid>("ElderlyId")
                        .HasColumnType("uuid")
                        .HasColumnName("elderly_id");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("ObservedCondition")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("observed_condition");

                    b.Property<DateTime>("StartedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_on_utc");

                    b.Property<DateTime>("SubmittedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("ux_visit_reports_booking");

                    b.HasIndex("ElderlyId");

                    b.HasIndex("FamilyId", "SubmittedOnUtc");

                    b.ToTable("visit_reports", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.FamilySubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenewEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renew_enabled");

                    b.Property<DateTime?>("CancellationRequestedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancellation_requested_on_utc");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateTime>("CurrentPeriodEndsOnUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("current_period_ends_on_utc");

                    b.Property<decimal?>("CurrentPeriodGross")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_period_gross");

                    b.Property<decimal?>("CurrentPeriodTaxRatePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("current_period_tax_rate_percentage");

                    b.Property<int>("Cycle")
                        .HasColumnType("integer")
                        .HasColumnName("cycle");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<DateTime?>("LastRenewalFailedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_renewal_failed_on_utc");

                    b.Property<Guid>("LifecycleVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("lifecycle_version");

                    b.Property<int>("MemberLimitKind")
                        .HasColumnType("integer")
                        .HasColumnName("member_limit_kind");

                    b.Property<int?>("MemberLimitValue")
                        .HasColumnType("integer")
                        .HasColumnName("member_limit_value");

                    b.Property<int>("MonthlyBookingLimitKind")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_booking_limit_kind");

                    b.Property<int?>("MonthlyBookingLimitValue")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_booking_limit_value");

                    b.Property<string>("PaymobLastCallbackKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("paymob_last_callback_key");

                    b.Property<DateTime?>("PaymobNextBillingOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paymob_next_billing_on_utc");

                    b.Property<string>("PaymobSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_subscription_id");

                    b.Property<string>("PaymobSubscriptionState")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_subscription_state");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_key");

                    b.Property<int>("PlanVersion")
                        .HasColumnType("integer")
                        .HasColumnName("plan_version");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("RenewalGraceEndsOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renewal_grace_ends_on_utc");

                    b.Property<int>("Rollover")
                        .HasColumnType("integer")
                        .HasColumnName("rollover");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .IsUnique()
                        .HasDatabaseName("ux_family_subscriptions_current")
                        .HasFilter("is_current = true");

                    b.HasIndex("PaymobSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_family_subscriptions_paymob_subscription_id")
                        .HasFilter("paymob_subscription_id IS NOT NULL");

                    b.ToTable("family_subscriptions", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.PaymobSubscriptionCallback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CallbackKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("callback_key");

                    b.Property<string>("PaymobRequestId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("paymob_request_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_subscription_id");

                    b.Property<DateTime>("ReceivedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_on_utc");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("trigger_type");

                    b.HasKey("Id");

                    b.HasIndex("CallbackKey")
                        .IsUnique()
                        .HasDatabaseName("ux_paymob_subscription_callbacks_key");

                    b.HasIndex("PaymobRequestId")
                        .IsUnique()
                        .HasDatabaseName("ux_paymob_subscription_callbacks_request_id")
                        .HasFilter("paymob_request_id IS NOT NULL");

                    b.ToTable("paymob_subscription_callbacks", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.PaymobSubscriptionIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("FamilySubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_subscription_id");

                    b.Property<Guid>("PaymentAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_attempt_id");

                    b.Property<string>("ProviderSubscriptionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_subscription_id");

                    b.HasKey("Id");

                    b.HasIndex("FamilySubscriptionId");

                    b.HasIndex("PaymentAttemptId");

                    b.HasIndex("ProviderSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_paymob_subscription_identities_provider_subscription_id");

                    b.ToTable("paymob_subscription_identities", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionCoupon", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<DateTime>("ExpiresOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_on_utc");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_version_id");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_coupons_code");

                    b.HasIndex("PlanVersionId")
                        .HasDatabaseName("ix_subscription_coupons_plan_version_id");

                    b.ToTable("subscription_coupons", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("invoice_number");

                    b.Property<DateTime>("IssuedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_on_utc");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<Guid>("OwnerFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<Guid?>("PaymentAttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_attempt_id");

                    b.Property<string>("PdfStorageKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("pdf_storage_key");

                    b.Property<DateTime>("PeriodEndsOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_ends_on_utc");

                    b.Property<DateTime>("PeriodStartsOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_starts_on_utc");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_key");

                    b.Property<int>("PlanVersion")
                        .HasColumnType("integer")
                        .HasColumnName("plan_version");

                    b.Property<string>("ProviderEventId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_event_id");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TotalPayable")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_payable");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("PaymentAttemptId")
                        .IsUnique()
                        .HasFilter("payment_attempt_id IS NOT NULL");

                    b.HasIndex("ProviderEventId")
                        .IsUnique()
                        .HasFilter("provider_event_id IS NOT NULL");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("subscription_invoices", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPaymentAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("coupon_code");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal>("DiscountPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<DateTime?>("FailedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_on_utc");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_id");

                    b.Property<bool>("IsPlanChange")
                        .HasColumnType("boolean")
                        .HasColumnName("is_plan_change");

                    b.Property<bool>("IsRenewal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_renewal");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<string>("PaymobInitialTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_initial_transaction_id");

                    b.Property<string>("PaymobOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_order_id");

                    b.Property<string>("PaymobSubscriptionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_subscription_id");

                    b.Property<string>("PaymobTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("paymob_transaction_id");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_key");

                    b.Property<int>("PlanVersion")
                        .HasColumnType("integer")
                        .HasColumnName("plan_version");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_version_id");

                    b.Property<decimal?>("ProratedCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("prorated_credit");

                    b.Property<DateTime?>("SettledOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_on_utc");

                    b.Property<DateTime?>("SourcePeriodEndsOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_period_ends_on_utc");

                    b.Property<decimal?>("SourcePeriodGross")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("source_period_gross");

                    b.Property<decimal?>("SourcePeriodTaxRatePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("source_period_tax_rate_percentage");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRatePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate_percentage");

                    b.Property<decimal>("TaxableAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("taxable_amount");

                    b.Property<decimal>("TotalPayable")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_payable");

                    b.HasKey("Id");

                    b.HasIndex("PaymobOrderId")
                        .IsUnique();

                    b.HasIndex("PaymobSubscriptionId")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_payment_attempts_paymob_subscription_id")
                        .HasFilter("paymob_subscription_id IS NOT NULL");

                    b.HasIndex("PlanVersionId");

                    b.HasIndex("FamilyId", "Status");

                    b.HasIndex("SubscriptionId", "IsRenewal", "Status");

                    b.ToTable("subscription_payment_attempts", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPlanRetirementAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("actor_role");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<bool>("NewAvailability")
                        .HasColumnType("boolean")
                        .HasColumnName("new_availability");

                    b.Property<bool>("OldAvailability")
                        .HasColumnType("boolean")
                        .HasColumnName("old_availability");

                    b.Property<string>("PlanKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_key");

                    b.Property<int>("PlanVersion")
                        .HasColumnType("integer")
                        .HasColumnName("plan_version");

                    b.Property<Guid>("PlanVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_version_id");

                    b.Property<DateTime>("RetiredOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retired_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("PlanVersionId")
                        .HasDatabaseName("ix_subscription_plan_retirement_audits_plan_version_id");

                    b.ToTable("subscription_plan_retirement_audits", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPlanVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<int>("Cycle")
                        .HasColumnType("integer")
                        .HasColumnName("cycle");

                    b.Property<bool>("IsAvailableForNewSales")
                        .IsConcurrencyToken()
                        .HasColumnType("boolean")
                        .HasColumnName("is_available_for_new_sales");

                    b.Property<bool>("IsPublished")
                        .IsConcurrencyToken()
                        .HasColumnType("boolean")
                        .HasColumnName("is_published");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("plan_key");

                    b.Property<int>("MemberLimitKind")
                        .HasColumnType("integer")
                        .HasColumnName("member_limit_kind");

                    b.Property<int?>("MemberLimitValue")
                        .HasColumnType("integer")
                        .HasColumnName("member_limit_value");

                    b.Property<int>("MonthlyBookingLimitKind")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_booking_limit_kind");

                    b.Property<int?>("MonthlyBookingLimitValue")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_booking_limit_value");

                    b.Property<int?>("PaymobSubscriptionPlanId")
                        .HasColumnType("integer")
                        .HasColumnName("paymob_subscription_plan_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PublishedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_on_utc");

                    b.Property<int>("Rollover")
                        .HasColumnType("integer")
                        .HasColumnName("rollover");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Key", "Version")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_plan_versions_key_version");

                    b.ToTable("subscription_plan_versions", "families");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionTaxRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("EffectiveOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_on_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("RatePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("rate_percentage");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_tax_rules_active")
                        .HasFilter("\"is_active\" = TRUE");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ux_subscription_tax_rules_version");

                    b.ToTable("subscription_tax_rules", "families", t =>
                        {
                            t.HasCheckConstraint("ck_subscription_tax_rules_rate_percentage", "\"rate_percentage\" BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_subscription_tax_rules_version_positive", "\"version\" > 0");
                        });
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.AssessmentQuestion", b =>
                {
                    b.OwnsMany("Sanad.Modules.Families.Domain.Assessments.AssessmentOption", "Options", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("ArabicText")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("arabic_text");

                            b1.Property<string>("EnglishText")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)")
                                .HasColumnName("english_text");

                            b1.Property<int>("Order")
                                .HasColumnType("integer")
                                .HasColumnName("order");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid")
                                .HasColumnName("question_id");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer")
                                .HasColumnName("weight");

                            b1.HasKey("Id");

                            b1.HasIndex("QuestionId", "Order");

                            b1.ToTable("assessment_options", "families");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.Navigation("Options");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Assessments.CareAssessment", b =>
                {
                    b.OwnsMany("Sanad.Modules.Families.Domain.Assessments.CareAssessmentAnswer", "Answers", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("AssessmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("assessment_id");

                            b1.Property<Guid>("QuestionId")
                                .HasColumnType("uuid")
                                .HasColumnName("question_id");

                            b1.Property<int>("ScoreSnapshot")
                                .HasColumnType("integer")
                                .HasColumnName("score_snapshot");

                            b1.Property<Guid>("SelectedOptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("selected_option_id");

                            b1.HasKey("Id");

                            b1.HasIndex("AssessmentId");

                            b1.ToTable("care_assessment_answers", "families");

                            b1.WithOwner()
                                .HasForeignKey("AssessmentId");
                        });

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Bookings.Booking", b =>
                {
                    b.OwnsOne("Sanad.BuildingBlocks.Domain.ValueObjects.BookingPriceSnapshot", "PriceSnapshot", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("BaseCaregiverFee")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_base_fee");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("price_currency");

                            b1.Property<decimal>("PlatformFeeAmount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_platform_fee_amount");

                            b1.Property<decimal>("PlatformFeePercentage")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("price_platform_fee_percentage");

                            b1.Property<decimal>("TotalPayableAmount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("price_total_payable_amount");

                            b1.HasKey("BookingId");

                            b1.ToTable("bookings", "families");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.OwnsMany("Sanad.Modules.Families.Domain.Bookings.PaymentTransaction", "PaymentTransactions", b1 =>
                        {
                            b1.Property<Guid>("BookingId")
                                .HasColumnType("uuid")
                                .HasColumnName("booking_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("amount");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on_utc");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("currency");

                            b1.Property<DateTime?>("FailedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("failed_on_utc");

                            b1.Property<int>("Method")
                                .HasColumnType("integer")
                                .HasColumnName("method");

                            b1.Property<string>("PaymobOrderId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("paymob_order_id");

                            b1.Property<string>("PaymobTransactionId")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("paymob_transaction_id");

                            b1.Property<DateTime?>("RefundedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("refunded_on_utc");

                            b1.Property<DateTime?>("SettledOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("settled_on_utc");

                            b1.Property<int>("Status")
                                .HasColumnType("integer")
                                .HasColumnName("status");

                            b1.HasKey("BookingId", "Id");

                            b1.HasIndex("PaymobOrderId");

                            b1.HasIndex("PaymobTransactionId");

                            b1.ToTable("payment_transactions", "families");

                            b1.WithOwner()
                                .HasForeignKey("BookingId");
                        });

                    b.Navigation("PaymentTransactions");

                    b.Navigation("PriceSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Bookings.BookingCancellationFact", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Elderlies.Elderly", b =>
                {
                    b.OwnsOne("Sanad.Modules.Families.Domain.Elderlies.Medical.ElderlyMedicalProfile", "MedicalProfile", b1 =>
                        {
                            b1.Property<Guid>("ElderlyId")
                                .HasColumnType("uuid")
                                .HasColumnName("elderly_id");

                            b1.Property<string>("Allergies")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("allergies");

                            b1.Property<int>("BloodType")
                                .HasColumnType("integer")
                                .HasColumnName("blood_type");

                            b1.Property<string>("ChronicConditions")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("chronic_conditions");

                            b1.Property<int?>("HeightCm")
                                .HasColumnType("integer")
                                .HasColumnName("height_cm");

                            b1.Property<string>("MedicalHistory")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("medical_history");

                            b1.Property<DateTime>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on_utc");

                            b1.Property<decimal?>("WeightKg")
                                .HasPrecision(5, 1)
                                .HasColumnType("numeric(5,1)")
                                .HasColumnName("weight_kg");

                            b1.HasKey("ElderlyId");

                            b1.ToTable("elderly_medical_profiles", "families");

                            b1.WithOwner()
                                .HasForeignKey("ElderlyId");
                        });

                    b.Navigation("MedicalProfile");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Families.Family", b =>
                {
                    b.OwnsMany("Sanad.Modules.Families.Domain.Families.FamilyMember", "Members", b1 =>
                        {
                            b1.Property<Guid>("FamilyId")
                                .HasColumnType("uuid")
                                .HasColumnName("family_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("user_id");

                            b1.Property<Guid>("AddedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("added_by_user_id");

                            b1.Property<DateTime>("JoinedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("joined_on_utc");

                            b1.Property<int>("RelationshipType")
                                .HasColumnType("integer")
                                .HasColumnName("relationship_type");

                            b1.Property<int>("Role")
                                .HasColumnType("integer")
                                .HasColumnName("role");

                            b1.HasKey("FamilyId", "Id");

                            b1.ToTable("family_members", "families");

                            b1.WithOwner()
                                .HasForeignKey("FamilyId");
                        });

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Reports.MedicalReport", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.Families.Domain.Elderlies.Elderly", null)
                        .WithMany()
                        .HasForeignKey("ElderlyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.Families.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Reports.VisitReport", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Bookings.Booking", null)
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.Families.Domain.Elderlies.Elderly", null)
                        .WithMany()
                        .HasForeignKey("ElderlyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.Families.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.FamilySubscription", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionBenefit", "Benefits", b1 =>
                        {
                            b1.Property<Guid>("FamilySubscriptionId")
                                .HasColumnType("uuid")
                                .HasColumnName("family_subscription_id");

                            b1.Property<int>("Key")
                                .HasColumnType("integer")
                                .HasColumnName("benefit_key");

                            b1.Property<bool>("IsIncluded")
                                .HasColumnType("boolean")
                                .HasColumnName("is_included");

                            b1.HasKey("FamilySubscriptionId", "Key");

                            b1.ToTable("family_subscription_benefits", "families");

                            b1.WithOwner()
                                .HasForeignKey("FamilySubscriptionId");
                        });

                    b.OwnsOne("Sanad.Modules.Families.Domain.Subscriptions.PendingSubscriptionDowngrade", "PendingDowngrade", b1 =>
                        {
                            b1.Property<Guid>("FamilySubscriptionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("pending_downgrade_currency");

                            b1.Property<int>("Cycle")
                                .HasColumnType("integer")
                                .HasColumnName("pending_downgrade_cycle");

                            b1.Property<int>("MemberLimitKind")
                                .HasColumnType("integer")
                                .HasColumnName("pending_downgrade_member_limit_kind");

                            b1.Property<int?>("MemberLimitValue")
                                .HasColumnType("integer")
                                .HasColumnName("pending_downgrade_member_limit_value");

                            b1.Property<int>("MonthlyBookingLimitKind")
                                .HasColumnType("integer")
                                .HasColumnName("pending_downgrade_monthly_booking_limit_kind");

                            b1.Property<int?>("MonthlyBookingLimitValue")
                                .HasColumnType("integer")
                                .HasColumnName("pending_downgrade_monthly_booking_limit_value");

                            b1.Property<string>("PlanKey")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("pending_downgrade_plan_key");

                            b1.Property<int>("PlanVersion")
                                .HasColumnType("integer")
                                .HasColumnName("pending_downgrade_plan_version");

                            b1.Property<decimal>("Price")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("pending_downgrade_price");

                            b1.Property<int>("Rollover")
                                .HasColumnType("integer")
                                .HasColumnName("pending_downgrade_rollover");

                            b1.HasKey("FamilySubscriptionId");

                            b1.ToTable("family_subscriptions", "families");

                            b1.WithOwner()
                                .HasForeignKey("FamilySubscriptionId");

                            b1.OwnsMany("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionBenefit", "Benefits", b2 =>
                                {
                                    b2.Property<Guid>("FamilySubscriptionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("family_subscription_id");

                                    b2.Property<int>("Key")
                                        .HasColumnType("integer")
                                        .HasColumnName("benefit_key");

                                    b2.Property<bool>("IsIncluded")
                                        .HasColumnType("boolean")
                                        .HasColumnName("is_included");

                                    b2.HasKey("FamilySubscriptionId", "Key");

                                    b2.ToTable("family_subscription_pending_downgrade_benefits", "families");

                                    b2.WithOwner()
                                        .HasForeignKey("FamilySubscriptionId");
                                });

                            b1.Navigation("Benefits");
                        });

                    b.Navigation("Benefits");

                    b.Navigation("PendingDowngrade");
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.PaymobSubscriptionIdentity", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Subscriptions.FamilySubscription", null)
                        .WithMany()
                        .HasForeignKey("FamilySubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPaymentAttempt", null)
                        .WithMany()
                        .HasForeignKey("PaymentAttemptId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionCoupon", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPlanVersion", null)
                        .WithMany()
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionInvoice", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPaymentAttempt", null)
                        .WithMany()
                        .HasForeignKey("PaymentAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sanad.Modules.Families.Domain.Subscriptions.FamilySubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPaymentAttempt", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Families.Family", null)
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPlanVersion", null)
                        .WithMany()
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sanad.Modules.Families.Domain.Subscriptions.FamilySubscription", null)
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPlanRetirementAudit", b =>
                {
                    b.HasOne("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPlanVersion", null)
                        .WithMany()
                        .HasForeignKey("PlanVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionPlanVersion", b =>
                {
                    b.OwnsMany("Sanad.Modules.Families.Domain.Subscriptions.SubscriptionBenefit", "Benefits", b1 =>
                        {
                            b1.Property<Guid>("SubscriptionPlanVersionId")
                                .HasColumnType("uuid")
                                .HasColumnName("subscription_plan_version_id");

                            b1.Property<int>("Key")
                                .HasColumnType("integer")
                                .HasColumnName("benefit_key");

                            b1.Property<bool>("IsIncluded")
                                .HasColumnType("boolean")
                                .HasColumnName("is_included");

                            b1.HasKey("SubscriptionPlanVersionId", "Key");

                            b1.ToTable("subscription_plan_version_benefits", "families");

                            b1.WithOwner()
                                .HasForeignKey("SubscriptionPlanVersionId");
                        });

                    b.Navigation("Benefits");
                });
#pragma warning restore 612, 618
        }
    }
}
