using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Sanad.BuildingBlocks.Domain.Primitives.Ids;
using Sanad.Modules.Families.Domain.HelpRequests;
namespace Sanad.Modules.Families.Infrastructure.Persistence.Configurations;
public sealed class ElderlyHelpRequestConfiguration : IEntityTypeConfiguration<ElderlyHelpRequest>
{ public void Configure(EntityTypeBuilder<ElderlyHelpRequest> b) { b.ToTable("elderly_help_requests"); b.HasKey(x => x.Id); b.Property(x => x.Id).ValueGeneratedNever(); b.Property(x => x.ElderlyIdentityUserId).HasConversion(x => x.Value, x => new UserId(x)).IsRequired(); b.Property(x => x.Status).HasConversion<int>().IsRequired(); foreach (var p in new[] { "ActorKey", "ActionKey", "NeedKey", "QualifierKey" }) b.Property<string?>(p).HasMaxLength(120); foreach (var p in new[] { "ActorArabicLabel", "ActorEnglishLabel", "ActionArabicLabel", "ActionEnglishLabel", "NeedArabicLabel", "NeedEnglishLabel", "QualifierArabicLabel", "QualifierEnglishLabel" }) b.Property<string?>(p).HasMaxLength(200); b.Property(x => x.CustomText).HasMaxLength(500); b.Property(x => x.IdempotencyKey).HasMaxLength(200).IsRequired(); b.HasIndex(x => new { x.ElderlyIdentityUserId, x.IdempotencyKey }).IsUnique(); b.HasIndex(x => x.CreatedOnUtc); b.HasMany(x => x.History).WithOne().HasForeignKey(x => x.HelpRequestId).OnDelete(DeleteBehavior.Cascade); b.Navigation(x => x.History).HasField("_history").UsePropertyAccessMode(PropertyAccessMode.Field); } }
public sealed class ElderlyHelpRequestHistoryConfiguration : IEntityTypeConfiguration<ElderlyHelpRequestHistory>
{ public void Configure(EntityTypeBuilder<ElderlyHelpRequestHistory> b) { b.ToTable("elderly_help_request_history"); b.HasKey(x => x.Id); b.Property(x => x.Id).ValueGeneratedNever(); b.Property(x => x.Action).HasConversion<int>(); b.Property(x => x.Status).HasConversion<int>(); b.Property(x => x.Reason).HasMaxLength(500); b.Property(x => x.ActorUserId).HasConversion(x => x.Value, x => new UserId(x)); b.HasIndex(x => new { x.HelpRequestId, x.OccurredOnUtc }); } }
