using Sanad.BuildingBlocks.Domain.Abstractions;
using Sanad.BuildingBlocks.Domain.Exceptions;
using Sanad.BuildingBlocks.Domain.Primitives.Ids;

namespace Sanad.Modules.Families.Domain.HelpRequests;
public enum ElderlyHelpRequestStatus { Pending = 1, Accepted = 2, InProgress = 3, Resolved = 4, Rejected = 5, Cancelled = 6, Reopened = 7, Acknowledged = 8 }
public enum ElderlyHelpRequestHistoryAction { Created = 1, Accepted = 2, Started = 3, Resolved = 4, Rejected = 5, Cancelled = 6, Reopened = 7, Acknowledged = 8 }
public sealed class ElderlyHelpRequest : AggregateRoot<Guid>
{
 private readonly List<ElderlyHelpRequestHistory> _history = [];
 private ElderlyHelpRequest() { }
 private ElderlyHelpRequest(Guid id, UserId elderly, Guid family, string actorKey, string actorAr, string actorEn, string actionKey, string actionAr, string actionEn, string needKey, string needAr, string needEn, string? qualifierKey, string? qualifierAr, string? qualifierEn, string? customText, string idem, DateTime now) : base(id)
 { ElderlyIdentityUserId = elderly; FamilyId = family; ActorKey = actorKey; ActorArabicLabel = actorAr; ActorEnglishLabel = actorEn; ActionKey = actionKey; ActionArabicLabel = actionAr; ActionEnglishLabel = actionEn; NeedKey = needKey; NeedArabicLabel = needAr; NeedEnglishLabel = needEn; QualifierKey = qualifierKey; QualifierArabicLabel = qualifierAr; QualifierEnglishLabel = qualifierEn; CustomText = customText; IdempotencyKey = idem; Status = ElderlyHelpRequestStatus.Pending; CreatedOnUtc = now; UpdatedOnUtc = now; }
 public UserId ElderlyIdentityUserId { get; private set; } public Guid FamilyId { get; private set; }
 public string ActorKey { get; private set; } = ""; public string ActorArabicLabel { get; private set; } = ""; public string ActorEnglishLabel { get; private set; } = "";
 public string ActionKey { get; private set; } = ""; public string ActionArabicLabel { get; private set; } = ""; public string ActionEnglishLabel { get; private set; } = "";
 public string NeedKey { get; private set; } = ""; public string NeedArabicLabel { get; private set; } = ""; public string NeedEnglishLabel { get; private set; } = "";
 public string? QualifierKey { get; private set; } public string? QualifierArabicLabel { get; private set; } public string? QualifierEnglishLabel { get; private set; } public string? CustomText { get; private set; }
 public string IdempotencyKey { get; private set; } = ""; public ElderlyHelpRequestStatus Status { get; private set; } public DateTime CreatedOnUtc { get; private set; } public DateTime UpdatedOnUtc { get; private set; }
 public IReadOnlyCollection<ElderlyHelpRequestHistory> History => _history.AsReadOnly();
 public static ElderlyHelpRequest Create(UserId elderly, Guid family, string actorKey, string actorAr, string actorEn, string actionKey, string actionAr, string actionEn, string needKey, string needAr, string needEn, string? qualifierKey, string? qualifierAr, string? qualifierEn, string? customText, string idempotencyKey)
 { if (elderly == UserId.Empty || family == Guid.Empty || string.IsNullOrWhiteSpace(idempotencyKey)) throw new DomainException("Help request identity and idempotency key are required."); if (customText is { Length: > 500 } || customText?.Contains('<') == true || customText?.Contains('>') == true) throw new DomainException("Custom text is invalid."); var x = new ElderlyHelpRequest(Guid.CreateVersion7(), elderly, family, actorKey, actorAr, actorEn, actionKey, actionAr, actionEn, needKey, needAr, needEn, qualifierKey, qualifierAr, qualifierEn, string.IsNullOrWhiteSpace(customText) ? null : customText.Trim(), idempotencyKey.Trim(), DateTime.UtcNow); x.AddHistory(ElderlyHelpRequestHistoryAction.Created, null, elderly); return x; }
 public void Transition(ElderlyHelpRequestHistoryAction action, string? reason, UserId actor) { var normalizedReason = string.IsNullOrWhiteSpace(reason) ? null : reason.Trim(); if (normalizedReason?.Length > 500 || ((action is ElderlyHelpRequestHistoryAction.Rejected or ElderlyHelpRequestHistoryAction.Reopened or ElderlyHelpRequestHistoryAction.Resolved) && normalizedReason is null)) throw new DomainException("A nonblank reason of at most 500 characters is required."); var next = action switch { ElderlyHelpRequestHistoryAction.Accepted when Status == ElderlyHelpRequestStatus.Pending => ElderlyHelpRequestStatus.Accepted, ElderlyHelpRequestHistoryAction.Started when Status is ElderlyHelpRequestStatus.Accepted or ElderlyHelpRequestStatus.Reopened => ElderlyHelpRequestStatus.InProgress, ElderlyHelpRequestHistoryAction.Resolved when Status == ElderlyHelpRequestStatus.InProgress => ElderlyHelpRequestStatus.Resolved, ElderlyHelpRequestHistoryAction.Rejected when Status == ElderlyHelpRequestStatus.Pending => ElderlyHelpRequestStatus.Rejected, ElderlyHelpRequestHistoryAction.Cancelled when Status == ElderlyHelpRequestStatus.Pending => ElderlyHelpRequestStatus.Cancelled, ElderlyHelpRequestHistoryAction.Reopened when Status is ElderlyHelpRequestStatus.Resolved or ElderlyHelpRequestStatus.Rejected => ElderlyHelpRequestStatus.Reopened, ElderlyHelpRequestHistoryAction.Acknowledged when Status == ElderlyHelpRequestStatus.Pending => ElderlyHelpRequestStatus.Acknowledged, _ => throw new DomainException("The help request transition is invalid.") }; Status = next; UpdatedOnUtc = DateTime.UtcNow; AddHistory(action, normalizedReason, actor); if (action == ElderlyHelpRequestHistoryAction.Reopened) { Status = ElderlyHelpRequestStatus.InProgress; UpdatedOnUtc = DateTime.UtcNow; } }
 private void AddHistory(ElderlyHelpRequestHistoryAction action, string? reason, UserId actor) => _history.Add(ElderlyHelpRequestHistory.Create(Id, action, Status, reason, actor));
}
public sealed class ElderlyHelpRequestHistory : Entity<Guid>
{ private ElderlyHelpRequestHistory() { } private ElderlyHelpRequestHistory(Guid request, ElderlyHelpRequestHistoryAction action, ElderlyHelpRequestStatus status, string? reason, UserId actor) : base(Guid.CreateVersion7()) { HelpRequestId = request; Action = action; Status = status; Reason = reason; ActorUserId = actor; OccurredOnUtc = DateTime.UtcNow; } public Guid HelpRequestId { get; private set; } public ElderlyHelpRequestHistoryAction Action { get; private set; } public ElderlyHelpRequestStatus Status { get; private set; } public string? Reason { get; private set; } public UserId ActorUserId { get; private set; } public DateTime OccurredOnUtc { get; private set; } public static ElderlyHelpRequestHistory Create(Guid id, ElderlyHelpRequestHistoryAction action, ElderlyHelpRequestStatus status, string? reason, UserId actor) => new(id, action, status, reason, actor); }
