// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanad.Modules.Caregivers.Infrastructure.Persistence;

#nullable disable

namespace Sanad.Modules.Caregivers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CaregiversDbContext))]
    [Migration("20260828081213_AddCaregiversAggregate")]
    partial class AddCaregiversAggregate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("caregivers")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Caregiver", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Availability")
                        .HasColumnType("integer")
                        .HasColumnName("availability");

                    b.Property<decimal>("AverageRating")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("average_rating");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("DetailedAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("detailed_address");

                    b.Property<int>("ReviewsCount")
                        .HasColumnType("integer")
                        .HasColumnName("reviews_count");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("status_reason");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("caregivers", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Lookups.AcademicDegree", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("arabic_name");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("english_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.ToTable("academic_degrees", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Lookups.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("arabic_name");

                    b.Property<Guid>("CityId")
                        .HasColumnType("uuid")
                        .HasColumnName("city_id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("english_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("areas", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Lookups.City", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("arabic_name");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("english_name");

                    b.Property<Guid>("GovernorateId")
                        .HasColumnType("uuid")
                        .HasColumnName("governorate_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("GovernorateId");

                    b.ToTable("cities", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Lookups.Governorate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("arabic_name");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("english_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.ToTable("governorates", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Lookups.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("arabic_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("english_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("languages", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Lookups.ProfessionalTitle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("arabic_name");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("english_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.ToTable("professional_titles", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Lookups.Service", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("arabic_name");

                    b.Property<int>("CaregiverType")
                        .HasColumnType("integer")
                        .HasColumnName("caregiver_type");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("english_name");

                    b.Property<string>("IconPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("icon_path");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverType");

                    b.ToTable("services", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Lookups.Specialization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArabicName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("arabic_name");

                    b.Property<int>("CaregiverType")
                        .HasColumnType("integer")
                        .HasColumnName("caregiver_type");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("english_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime>("UpdatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_on_utc");

                    b.HasKey("Id");

                    b.HasIndex("CaregiverType");

                    b.ToTable("specializations", "caregivers");
                });

            modelBuilder.Entity("Sanad.Modules.Caregivers.Domain.Caregivers.Caregiver", b =>
                {
                    b.OwnsMany("Sanad.Modules.Caregivers.Domain.Caregivers.CaregiverCertificate", "Certificates", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid")
                                .HasColumnName("caregiver_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_on_utc");

                            b1.Property<DateOnly?>("ExpiryDate")
                                .HasColumnType("date")
                                .HasColumnName("expiry_date");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("file_path");

                            b1.Property<string>("ReviewReason")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("review_reason");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("type");

                            b1.Property<DateTime>("UpdatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_on_utc");

                            b1.Property<int>("VerificationStatus")
                                .HasColumnType("integer")
                                .HasColumnName("verification_status");

                            b1.HasKey("CaregiverId", "Id");

                            b1.ToTable("caregiver_certificates", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");
                        });

                    b.OwnsOne("Sanad.Modules.Caregivers.Domain.Caregivers.CompanionCaregiverPricing", "CompanionPricing", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("EightHourDayPrice")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("companion_eight_hour_day_price");

                            b1.Property<decimal>("HourlyPrice")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("companion_hourly_price");

                            b1.Property<decimal>("OvernightPrice")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("companion_overnight_price");

                            b1.HasKey("CaregiverId");

                            b1.ToTable("caregivers", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");
                        });

                    b.OwnsOne("Sanad.Modules.Caregivers.Domain.Caregivers.CompanionCaregiverProfile", "CompanionProfile", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Biography")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("companion_biography");

                            b1.Property<Guid>("SpecializationId")
                                .HasColumnType("uuid")
                                .HasColumnName("companion_specialization_id");

                            b1.Property<int>("YearsOfExperience")
                                .HasColumnType("integer")
                                .HasColumnName("companion_years_of_experience");

                            b1.HasKey("CaregiverId");

                            b1.ToTable("caregivers", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");
                        });

                    b.OwnsOne("Sanad.Modules.Caregivers.Domain.Caregivers.CompanionWeeklySchedule", "CompanionSchedule", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid")
                                .HasColumnName("caregiver_id");

                            b1.HasKey("CaregiverId");

                            b1.ToTable("companion_schedules", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");

                            b1.OwnsMany("Sanad.Modules.Caregivers.Domain.Caregivers.CompanionAvailabilityWindow", "Windows", b2 =>
                                {
                                    b2.Property<Guid>("CompanionScheduleId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("companion_schedule_id");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("BookingType")
                                        .HasColumnType("integer")
                                        .HasColumnName("booking_type");

                                    b2.Property<int>("DayOfWeek")
                                        .HasColumnType("integer")
                                        .HasColumnName("day_of_week");

                                    b2.Property<TimeOnly>("EndTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("StartTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("start_time");

                                    b2.HasKey("CompanionScheduleId", "Id");

                                    b2.ToTable("companion_availability_windows", "caregivers");

                                    b2.WithOwner()
                                        .HasForeignKey("CompanionScheduleId");
                                });

                            b1.Navigation("Windows");
                        });

                    b.OwnsOne("Sanad.Modules.Caregivers.Domain.Caregivers.MedicalCaregiverPricing", "MedicalPricing", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("EightHourShiftPrice")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("medical_eight_hour_shift_price");

                            b1.Property<decimal>("HomeVisitPrice")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("medical_home_visit_price");

                            b1.Property<decimal>("TwelveHourShiftPrice")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("medical_twelve_hour_shift_price");

                            b1.Property<decimal>("TwentyFourHourShiftPrice")
                                .HasPrecision(12, 2)
                                .HasColumnType("numeric(12,2)")
                                .HasColumnName("medical_twenty_four_hour_shift_price");

                            b1.HasKey("CaregiverId");

                            b1.ToTable("caregivers", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");
                        });

                    b.OwnsOne("Sanad.Modules.Caregivers.Domain.Caregivers.MedicalCaregiverProfile", "MedicalProfile", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("AcademicDegreeId")
                                .HasColumnType("uuid")
                                .HasColumnName("medical_academic_degree_id");

                            b1.Property<string>("Biography")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("medical_biography");

                            b1.Property<string>("CurrentWorkplace")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("medical_current_workplace");

                            b1.Property<Guid>("ProfessionalTitleId")
                                .HasColumnType("uuid")
                                .HasColumnName("medical_professional_title_id");

                            b1.Property<Guid>("SpecializationId")
                                .HasColumnType("uuid")
                                .HasColumnName("medical_specialization_id");

                            b1.Property<int>("YearsOfExperience")
                                .HasColumnType("integer")
                                .HasColumnName("medical_years_of_experience");

                            b1.HasKey("CaregiverId");

                            b1.ToTable("caregivers", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");
                        });

                    b.OwnsOne("Sanad.Modules.Caregivers.Domain.Caregivers.MedicalWeeklySchedule", "MedicalSchedule", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid")
                                .HasColumnName("caregiver_id");

                            b1.HasKey("CaregiverId");

                            b1.ToTable("medical_schedules", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");

                            b1.OwnsMany("Sanad.Modules.Caregivers.Domain.Caregivers.MedicalHomeVisitWindow", "HomeVisitWindows", b2 =>
                                {
                                    b2.Property<Guid>("MedicalScheduleId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("medical_schedule_id");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("DayOfWeek")
                                        .HasColumnType("integer")
                                        .HasColumnName("day_of_week");

                                    b2.Property<TimeOnly>("EndTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("end_time");

                                    b2.Property<TimeOnly>("StartTime")
                                        .HasColumnType("time without time zone")
                                        .HasColumnName("start_time");

                                    b2.HasKey("MedicalScheduleId", "Id");

                                    b2.ToTable("medical_home_visit_windows", "caregivers");

                                    b2.WithOwner()
                                        .HasForeignKey("MedicalScheduleId");
                                });

                            b1.OwnsMany("Sanad.Modules.Caregivers.Domain.Caregivers.MedicalShiftAvailability", "Shifts", b2 =>
                                {
                                    b2.Property<Guid>("MedicalScheduleId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("medical_schedule_id");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("DayOfWeek")
                                        .HasColumnType("integer")
                                        .HasColumnName("day_of_week");

                                    b2.Property<int>("ShiftType")
                                        .HasColumnType("integer")
                                        .HasColumnName("shift_type");

                                    b2.HasKey("MedicalScheduleId", "Id");

                                    b2.ToTable("medical_shifts", "caregivers");

                                    b2.WithOwner()
                                        .HasForeignKey("MedicalScheduleId");
                                });

                            b1.Navigation("HomeVisitWindows");

                            b1.Navigation("Shifts");
                        });

                    b.OwnsMany("Sanad.Modules.Caregivers.Domain.Caregivers.Selections.CaregiverAreaSelection", "AreaSelections", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid")
                                .HasColumnName("caregiver_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("area_id");

                            b1.HasKey("CaregiverId", "Id");

                            b1.ToTable("caregiver_area_selections", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");
                        });

                    b.OwnsMany("Sanad.Modules.Caregivers.Domain.Caregivers.Selections.CaregiverLanguageSelection", "LanguageSelections", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid")
                                .HasColumnName("caregiver_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("language_id");

                            b1.HasKey("CaregiverId", "Id");

                            b1.ToTable("caregiver_language_selections", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");
                        });

                    b.OwnsMany("Sanad.Modules.Caregivers.Domain.Caregivers.Selections.CaregiverServiceSelection", "ServiceSelections", b1 =>
                        {
                            b1.Property<Guid>("CaregiverId")
                                .HasColumnType("uuid")
                                .HasColumnName("caregiver_id");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("service_id");

                            b1.HasKey("CaregiverId", "Id");

                            b1.ToTable("caregiver_service_selections", "caregivers");

                            b1.WithOwner()
                                .HasForeignKey("CaregiverId");
                        });

                    b.Navigation("AreaSelections");

                    b.Navigation("Certificates");

                    b.Navigation("CompanionPricing");

                    b.Navigation("CompanionProfile");

                    b.Navigation("CompanionSchedule");

                    b.Navigation("LanguageSelections");

                    b.Navigation("MedicalPricing");

                    b.Navigation("MedicalProfile");

                    b.Navigation("MedicalSchedule");

                    b.Navigation("ServiceSelections");
                });
#pragma warning restore 612, 618
        }
    }
}
