using Microsoft.EntityFrameworkCore;
using Sanad.BuildingBlocks.Application.CQRS;
using Sanad.BuildingBlocks.Application.Results;
using Sanad.Modules.Cms.Application.Abstractions.Data;
using Sanad.Modules.Cms.Domain.SentenceBuilder;

namespace Sanad.Modules.Cms.Application.SentenceBuilder;
public sealed record SentenceBuilderCatalogItem(Guid EntryId, Guid RevisionId, string StableKey, SentenceBuilderCategory Category, string ArabicLabel, string EnglishLabel, int DisplayOrder, int Version, bool IsActive, DateTime CreatedOnUtc);
public sealed record SentenceBuilderCatalogPage(IReadOnlyList<SentenceBuilderCatalogItem> Items, int Page, int PageSize, int TotalCount);
public sealed record UpsertSentenceBuilderCatalogCommand(string StableKey, SentenceBuilderCategory Category, string ArabicLabel, string EnglishLabel, int DisplayOrder) : ICommand<SentenceBuilderCatalogItem>;
public sealed record SetSentenceBuilderCatalogActiveCommand(Guid RevisionId, bool Active) : ICommand<SentenceBuilderCatalogItem>;
public sealed record ListSentenceBuilderCatalogQuery(SentenceBuilderCategory? Category = null, bool? Active = null, int Page = 1, int PageSize = 50) : IQuery<SentenceBuilderCatalogPage>;
public sealed record GetSentenceBuilderCatalogQuery(Guid RevisionId) : IQuery<SentenceBuilderCatalogItem>;
public static class SentenceBuilderCatalogErrors { public static readonly Error NotFound = new("Cms.SentenceBuilder.NotFound", "The sentence-builder catalog revision was not found."); public static readonly Error Invalid = new("Cms.SentenceBuilder.InvalidOperation", "The sentence-builder catalog operation is invalid."); public static readonly Error Conflict = new("Cms.SentenceBuilder.Conflict", "The sentence-builder catalog changed concurrently; retry the operation."); }
internal static class SentenceBuilderCatalogMapping { public static SentenceBuilderCatalogItem Map(SentenceBuilderCatalogEntry e, SentenceBuilderCatalogRevision r) => new(e.Id, r.Id, e.StableKey, e.Category, r.ArabicLabel, r.EnglishLabel, r.DisplayOrder, r.Version, r.IsActive, r.CreatedOnUtc); }
 public sealed class UpsertSentenceBuilderCatalogCommandHandler(ICmsDbContext db) : ICommandHandler<UpsertSentenceBuilderCatalogCommand, SentenceBuilderCatalogItem>
{ public async Task<Result<SentenceBuilderCatalogItem>> Handle(UpsertSentenceBuilderCatalogCommand r, CancellationToken ct) { try { if (!Enum.IsDefined(r.Category)) return SentenceBuilderCatalogErrors.Invalid; var e = await db.SentenceBuilderCatalogEntries.Include(x => x.Revisions).SingleOrDefaultAsync(x => x.StableKey == r.StableKey.Trim() && x.Category == r.Category, ct); if (e is null) { e = SentenceBuilderCatalogEntry.Create(r.StableKey, r.Category); db.SentenceBuilderCatalogEntries.Add(e); } foreach (var old in e.Revisions.Where(x => x.IsActive)) old.Deactivate(); var rev = e.AddRevision(r.ArabicLabel, r.EnglishLabel, r.DisplayOrder); rev.Activate(); await db.SaveChangesAsync(ct); return SentenceBuilderCatalogMapping.Map(e, rev); } catch (Sanad.BuildingBlocks.Domain.Exceptions.DomainException) { return SentenceBuilderCatalogErrors.Invalid; } catch (DbUpdateException) { return SentenceBuilderCatalogErrors.Conflict; } } }
public sealed class SetSentenceBuilderCatalogActiveCommandHandler(ICmsDbContext db) : ICommandHandler<SetSentenceBuilderCatalogActiveCommand, SentenceBuilderCatalogItem>
{ public async Task<Result<SentenceBuilderCatalogItem>> Handle(SetSentenceBuilderCatalogActiveCommand r, CancellationToken ct) { var rev = await db.SentenceBuilderCatalogRevisions.Include(x => x.CatalogEntry).SingleOrDefaultAsync(x => x.Id == r.RevisionId, ct); if (rev is null || rev.CatalogEntry is null) return SentenceBuilderCatalogErrors.NotFound; var entry = rev.CatalogEntry; if (r.Active) foreach (var old in await db.SentenceBuilderCatalogRevisions.Where(x => x.CatalogEntryId == entry.Id && x.IsActive).ToListAsync(ct)) old.Deactivate(); else rev.Deactivate(); if (r.Active) rev.Activate(); try { await db.SaveChangesAsync(ct); return SentenceBuilderCatalogMapping.Map(entry, rev); } catch (DbUpdateException) { return SentenceBuilderCatalogErrors.Conflict; } } }
public sealed class ListSentenceBuilderCatalogQueryHandler(ICmsDbContext db) : IQueryHandler<ListSentenceBuilderCatalogQuery, SentenceBuilderCatalogPage>
{ public async Task<Result<SentenceBuilderCatalogPage>> Handle(ListSentenceBuilderCatalogQuery r, CancellationToken ct) { var page = Math.Max(1, r.Page); var size = Math.Clamp(r.PageSize, 1, 100); var q = db.SentenceBuilderCatalogEntries.AsNoTracking().SelectMany(e => e.Revisions.Select(v => new { e, v })).AsQueryable(); if (r.Category.HasValue) q = q.Where(x => x.e.Category == r.Category); if (r.Active.HasValue) q = q.Where(x => x.v.IsActive == r.Active); var total = await q.CountAsync(ct); var rows = await q.OrderBy(x => x.e.Category).ThenBy(x => x.e.StableKey).ThenByDescending(x => x.v.Version).Skip((page - 1) * size).Take(size).ToListAsync(ct); return new SentenceBuilderCatalogPage(rows.Select(x => SentenceBuilderCatalogMapping.Map(x.e, x.v)).ToList(), page, size, total); } }
public sealed class GetSentenceBuilderCatalogQueryHandler(ICmsDbContext db) : IQueryHandler<GetSentenceBuilderCatalogQuery, SentenceBuilderCatalogItem>
{ public async Task<Result<SentenceBuilderCatalogItem>> Handle(GetSentenceBuilderCatalogQuery r, CancellationToken ct) { var x = await db.SentenceBuilderCatalogEntries.AsNoTracking().SelectMany(e => e.Revisions.Select(v => new { e, v })).SingleOrDefaultAsync(x => x.v.Id == r.RevisionId, ct); return x is null ? SentenceBuilderCatalogErrors.NotFound : SentenceBuilderCatalogMapping.Map(x.e, x.v); } }
