<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\BuildingBlocks\Infrastructure\Sanad.BuildingBlocks.Infrastructure\Sanad.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Application\Sanad.Modules.Caregivers.Application\Sanad.Modules.Caregivers.Application.csproj" />
    <ProjectReference Include="..\..\Domain\Sanad.Modules.Caregivers.Domain\Sanad.Modules.Caregivers.Domain.csproj" />
  </ItemGroup>

</Project>