// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanad.Modules.Finance.Infrastructure;

#nullable disable

namespace Sanad.Modules.Finance.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    partial class FinanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("finance")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanad.Modules.Finance.Domain.PlatformChargeRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on_utc");

                    b.Property<DateTime>("EffectiveOnUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_on_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("PlatformFeeRatePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("platform_fee_rate_percentage");

                    b.Property<decimal>("TaxRatePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("tax_rate_percentage");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ux_platform_charge_rules_active")
                        .HasFilter("\"is_active\" = TRUE");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ux_platform_charge_rules_version");

                    b.ToTable("platform_charge_rules", "finance", t =>
                        {
                            t.HasCheckConstraint("ck_platform_charge_rules_fee_rate", "platform_fee_rate_percentage BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_platform_charge_rules_tax_rate", "tax_rate_percentage BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_platform_charge_rules_version", "version > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
